"""migrate1

Revision ID: 036ae1c7365e
Revises: d315a6bcb908
Create Date: 2022-02-24 19:48:50.118890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036ae1c7365e'
down_revision = 'd315a6bcb908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goal1_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal1_id', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
