"""Initial migration.

Revision ID: 3238118c412e
Revises: e655888bb43f
Create Date: 2022-02-24 19:46:32.562437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3238118c412e'
down_revision = 'e655888bb43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal1_id', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('goal2_id', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('goal3_id', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('goal1_progress', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('goal2_progress', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('goal3_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goal3_progress')
    op.drop_column('user', 'goal2_progress')
    op.drop_column('user', 'goal1_progress')
    op.drop_column('user', 'goal3_id')
    op.drop_column('user', 'goal2_id')
    op.drop_column('user', 'goal1_id')
    # ### end Alembic commands ###
