"""Initial migration.

Revision ID: 649d3ebd7b9c
Revises: 3238118c412e
Create Date: 2022-02-25 00:16:37.627606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649d3ebd7b9c'
down_revision = '3238118c412e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal1_required', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('goal2_required', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('goal3_required', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goal3_required')
    op.drop_column('user', 'goal2_required')
    op.drop_column('user', 'goal1_required')
    # ### end Alembic commands ###
